# Pre-commit configuration for 'we' development tool
# Implements Phase 3 quality gates per NEW_CHANGES.MD

repos:
  # Shell quality gates
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: ShellCheck (shell script analysis)
        args: [--severity=warning]
        files: \.(sh|bash)$
        exclude: ^\.venv/

  - repo: https://github.com/mvdan/sh
    rev: v3.8.0
    hooks:
      - id: shfmt
        name: shfmt (shell script formatter)
        args: [-w, -s, -i, "2"]
        files: \.(sh|bash)$
        exclude: ^\.venv/

  # Python quality gates  
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Black (Python formatter)
        files: \.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: Ruff (Python linter)
        args: [--fix]
        files: \.py$
      - id: ruff-format
        name: Ruff (Python formatter)
        files: \.py$

  # General quality gates
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable